import type { BJCPStyle } from '@/lib/brewing/types/style'

/**
 * BJCP 2021 Style Guidelines — top 20 most-brewed styles for Phase 1.
 * Source: https://www.bjcp.org/style/2021/
 */
export const BJCP_2021_STYLES: BJCPStyle[] = [
  {
    id: '1A',
    categoryNumber: '1',
    categoryName: 'Standard American Beer',
    name: 'American Light Lager',
    vitalStats: {
      OG: [1.028, 1.04],
      FG: [0.998, 1.008],
      IBU: [8, 12],
      SRM: [2, 3],
      ABV: [2.8, 4.2],
    },
    description_md: 'Highly carbonated, very light-bodied, nearly flavorless lager.',
  },
  {
    id: '1C',
    categoryNumber: '1',
    categoryName: 'Standard American Beer',
    name: 'Cream Ale',
    vitalStats: {
      OG: [1.042, 1.055],
      FG: [1.006, 1.012],
      IBU: [8, 20],
      SRM: [2.5, 5],
      ABV: [4.2, 5.6],
    },
    description_md: 'Pale, refreshing, well-attenuated American ale.',
  },
  {
    id: '2A',
    categoryNumber: '2',
    categoryName: 'International Lager',
    name: 'International Pale Lager',
    vitalStats: {
      OG: [1.042, 1.05],
      FG: [1.008, 1.012],
      IBU: [18, 25],
      SRM: [2, 6],
      ABV: [4.6, 6.0],
    },
    description_md: 'A highly attenuated pale lager without distinctive character.',
  },
  {
    id: '5B',
    categoryNumber: '5',
    categoryName: 'Pale Bitter European Beer',
    name: 'Kölsch',
    vitalStats: {
      OG: [1.044, 1.05],
      FG: [1.007, 1.011],
      IBU: [18, 30],
      SRM: [3.5, 5],
      ABV: [4.4, 5.2],
    },
    description_md: 'A clean, crisp, delicately balanced beer from Köln, Germany.',
  },
  {
    id: '5D',
    categoryNumber: '5',
    categoryName: 'Pale Bitter European Beer',
    name: 'German Pils',
    vitalStats: {
      OG: [1.044, 1.05],
      FG: [1.008, 1.013],
      IBU: [22, 40],
      SRM: [2, 5],
      ABV: [4.4, 5.2],
    },
    description_md: 'A light-bodied, highly-attenuated, gold-colored Pilsner.',
  },
  {
    id: '9A',
    categoryNumber: '9',
    categoryName: 'Strong European Beer',
    name: 'Doppelbock',
    vitalStats: {
      OG: [1.072, 1.112],
      FG: [1.016, 1.024],
      IBU: [16, 26],
      SRM: [6, 25],
      ABV: [7.0, 10.0],
    },
    description_md: 'A strong, rich, very malty German lager.',
  },
  {
    id: '10A',
    categoryNumber: '10',
    categoryName: 'German Wheat Beer',
    name: 'Weissbier',
    vitalStats: {
      OG: [1.044, 1.052],
      FG: [1.01, 1.014],
      IBU: [8, 15],
      SRM: [2, 6],
      ABV: [4.3, 5.6],
    },
    description_md: 'Refreshing wheat-based ale with banana and clove yeast character.',
  },
  {
    id: '12A',
    categoryNumber: '12',
    categoryName: 'Pale Commonwealth Beer',
    name: 'British Golden Ale',
    vitalStats: {
      OG: [1.038, 1.053],
      FG: [1.006, 1.012],
      IBU: [20, 45],
      SRM: [2, 6],
      ABV: [3.8, 5.0],
    },
    description_md: 'A pale, refreshing, hop-forward British ale.',
  },
  {
    id: '13B',
    categoryNumber: '13',
    categoryName: 'Brown British Beer',
    name: 'British Brown Ale',
    vitalStats: {
      OG: [1.04, 1.052],
      FG: [1.008, 1.013],
      IBU: [20, 30],
      SRM: [12, 22],
      ABV: [4.2, 5.4],
    },
    description_md: 'A moderate-strength British brown ale with caramel/nutty character.',
  },
  {
    id: '14B',
    categoryNumber: '14',
    categoryName: 'Scottish Ale',
    name: 'Scottish Heavy',
    vitalStats: {
      OG: [1.035, 1.04],
      FG: [1.01, 1.015],
      IBU: [10, 20],
      SRM: [13, 22],
      ABV: [3.2, 3.9],
    },
    description_md: 'Malt-focused Scottish ale, low bitterness.',
  },
  {
    id: '15A',
    categoryNumber: '15',
    categoryName: 'Irish Beer',
    name: 'Irish Red Ale',
    vitalStats: {
      OG: [1.036, 1.046],
      FG: [1.01, 1.014],
      IBU: [18, 28],
      SRM: [9, 14],
      ABV: [3.8, 5.0],
    },
    description_md: 'Easy-drinking, slightly malty Irish red.',
  },
  {
    id: '15B',
    categoryNumber: '15',
    categoryName: 'Irish Beer',
    name: 'Irish Stout',
    vitalStats: {
      OG: [1.036, 1.044],
      FG: [1.007, 1.011],
      IBU: [25, 45],
      SRM: [25, 40],
      ABV: [4.0, 4.5],
    },
    description_md: 'The dry roasted Irish stout — coffee, chocolate, dry finish.',
  },
  {
    id: '16D',
    categoryNumber: '16',
    categoryName: 'Dark British Beer',
    name: 'Foreign Extra Stout',
    vitalStats: {
      OG: [1.056, 1.075],
      FG: [1.01, 1.018],
      IBU: [50, 70],
      SRM: [30, 40],
      ABV: [6.3, 8.0],
    },
    description_md: 'Strong, bold, roasty stout for export.',
  },
  {
    id: '18A',
    categoryNumber: '18',
    categoryName: 'Pale American Ale',
    name: 'Blonde Ale',
    vitalStats: {
      OG: [1.038, 1.054],
      FG: [1.008, 1.013],
      IBU: [15, 28],
      SRM: [3, 6],
      ABV: [3.8, 5.5],
    },
    description_md: 'Light, refreshing, lightly hopped American ale.',
  },
  {
    id: '18B',
    categoryNumber: '18',
    categoryName: 'Pale American Ale',
    name: 'American Pale Ale',
    vitalStats: {
      OG: [1.045, 1.06],
      FG: [1.01, 1.015],
      IBU: [30, 50],
      SRM: [5, 10],
      ABV: [4.5, 6.2],
    },
    description_md: 'Pale, refreshing, hoppy American ale.',
  },
  {
    id: '19A',
    categoryNumber: '19',
    categoryName: 'Amber and Brown American Beer',
    name: 'American Amber Ale',
    vitalStats: {
      OG: [1.045, 1.06],
      FG: [1.01, 1.015],
      IBU: [25, 40],
      SRM: [10, 17],
      ABV: [4.5, 6.2],
    },
    description_md: 'American hops + caramel malts. Balanced.',
  },
  {
    id: '20A',
    categoryNumber: '20',
    categoryName: 'American Porter and Stout',
    name: 'American Porter',
    vitalStats: {
      OG: [1.05, 1.07],
      FG: [1.012, 1.018],
      IBU: [25, 50],
      SRM: [22, 40],
      ABV: [4.8, 6.5],
    },
    description_md: 'Substantial dark malty ale; chocolate, roast, hops.',
  },
  {
    id: '21A',
    categoryNumber: '21',
    categoryName: 'IPA',
    name: 'American IPA',
    vitalStats: {
      OG: [1.056, 1.07],
      FG: [1.008, 1.014],
      IBU: [40, 70],
      SRM: [6, 14],
      ABV: [5.5, 7.5],
    },
    description_md: 'Hoppy, bitter, moderately strong American pale ale.',
  },
  {
    id: '21B',
    categoryNumber: '21',
    categoryName: 'IPA',
    name: 'Specialty IPA: New England IPA',
    vitalStats: {
      OG: [1.06, 1.085],
      FG: [1.01, 1.015],
      IBU: [25, 60],
      SRM: [3, 7],
      ABV: [6.0, 9.0],
    },
    description_md: 'Hazy, juicy, tropical-fruit-forward IPA.',
  },
  {
    id: '22A',
    categoryNumber: '22',
    categoryName: 'Strong American Ale',
    name: 'Double IPA',
    vitalStats: {
      OG: [1.065, 1.085],
      FG: [1.008, 1.018],
      IBU: [60, 120],
      SRM: [6, 14],
      ABV: [7.5, 10.0],
    },
    description_md: 'Intensely hoppy, very strong pale ale.',
  },
]

export function findStyle(id: string): BJCPStyle | undefined {
  return BJCP_2021_STYLES.find((s) => s.id === id)
}
